spring.application.name=pokepedia
server.port=5000

pokeapi.base-url=https://pokeapi.co/api/v2

spring.cache.type=caffeine
spring.cache.cache-names=pokemon-species
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=3600s
